import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Providers from "./Providers";

const poppins = Poppins({  weight: ['400', '700'],
style: ['normal'],
subsets: ['latin'],
display: 'swap', });

export const metadata: Metadata = {
  title: 'BlueVotes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}><Providers>{children} </Providers>{" "}</body>
    </html>
  )
}
